# ==============================================================================
# deploy/nodes.conf — конфигурация узлов федеративной системы
# ==============================================================================

# Сервер
SERVER_EXT=84.201.165.255
SERVER_INT=10.10.0.30

# Клиенты
# CLIENT_N     — внешний IP (обновлять при перезапуске VM)
# CLIENT_N_INT — внутренний IP (не меняется)
# CLIENT_N_NAME — имя VM (не меняется)
CLIENT_1_NAME=fl-client1
CLIENT_1=158.160.26.243
CLIENT_1_INT=10.10.0.33
CLIENT_1_CORES=2

CLIENT_2_NAME=fl-client2
CLIENT_2=178.154.218.78
CLIENT_2_INT=10.10.0.16
CLIENT_2_CORES=2

CLIENT_3_NAME=fl-client3
CLIENT_3=158.160.84.70
CLIENT_3_INT=10.10.0.12
CLIENT_3_CORES=4

CLIENT_4_NAME=fl-client4
CLIENT_4=89.169.175.199
CLIENT_4_INT=10.10.0.9
CLIENT_4_CORES=4

CLIENT_5_NAME=fl-client5
CLIENT_5=89.169.177.11
CLIENT_5_INT=10.10.0.34
CLIENT_5_CORES=8

CLIENT_6_NAME=fl-client6
CLIENT_6=89.169.163.138
CLIENT_6_INT=10.10.0.17
CLIENT_6_CORES=8

# SSH
SSH_USER=gleb
SSH_KEY_WIN=/mnt/c/Users/listr/.ssh/admin-fl

# Путь к проекту на удалённых машинах
REMOTE_DIR=/home/gleb/ddl
